name: clang-tidy-review

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt install qt6-base-dev libqt6opengl6-dev libglvnd-dev libeigen3-dev zlib1g-dev libfftw3-dev ninja-build

    - name: Run CMake
      run: cmake . -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

    - uses: ZedThree/clang-tidy-review@v0.21.0
      id: review
      with:
        apt_packages: g++,qt6-base-dev,libqt6opengl6-dev,libglvnd-dev,zlib1g-dev,libfftw3-dev,ninja-build
        config_file: .clang-tidy
        clang_tidy_version: 16

    - uses: ZedThree/clang-tidy-review/upload@v0.21.0
      id: upload-review
